### ISSUE TITLE
Improve VGA signal quality a bit

### ISSUE THREAD

**Issue by fdziarmagowski** [slu4coder/The-Minimal-64-Home-Computer#17]
There are visible vertical lines when displaying content with lots of "white" pixels.
I found that adding an additional decoupling capacitor (100n) to U44 directly to pins 1 and 16 improved the picture quality in such case.
One could use a socket with a with a decoupling capacitor to avoid changes to the layout, so this is more like a feature request than a bug report.

Thanks!

**Comment by slu4coder** [comment]
On my two boards, I cannot confirm any vertical lines in the output with the present design.
U44 is indeed the 74HC166 shift register generating the pixel stream for the VGA monitor. A 100nF cap doesn't hurt.
But, I'd first investigate a possible problem with the supply voltage on your board, Fryderyk, probably caused by a bad IC.
In such a case, the 100nF cap would just cover up a deeper problem.

**Comment by fdziarmagowski** [comment]
I'm at ~180 mA with keyboard connected. As you know my PCB has some other issues (which can be related), but power draw is not really an issue. I don't want to "cross post" the issues.
Thanks for looking at this small issue!
