### ISSUE TITLE
Newly soldered Minimal64 not working

### ISSUE THREAD

**Issue by denjhang** [slu4coder/The-Minimal-64-Home-Computer#19]
I just finished soldering a Minimal64. I used 628128 instead of as6c1008. I found that my Minimal64 currently cannot be turned on. Nothing is output on the VGA and no characters appear on the UART.

**Comment by denjhang** [comment]
![96dfc5b5f2afdfa06a051bdcb68b3087](https://github.com/slu4coder/The-Minimal-64-Home-Computer/assets/61811583/5a7cc1b0-fd5c-451b-95fd-c094aacfd2bb)
![beb44abf426a3a673e963851c44653f5](https://github.com/slu4coder/The-Minimal-64-Home-Computer/assets/61811583/1b918d70-1064-4cdc-9d14-24934c542505)

**Comment by denjhang** [comment]
I tried pressing the reset button and the UART gave me a garbled code every time it reset.

**Comment by denjhang** [comment]
![44F319FAEF171DE1DA71924767A2E8E8](https://github.com/slu4coder/The-Minimal-64-Home-Computer/assets/61811583/b850e700-ac93-4625-8159-3e4a6d6afbaa)
![192D948764A971F09644A3C48F8959B0](https://github.com/slu4coder/The-Minimal-64-Home-Computer/assets/61811583/72a57f5c-a2b7-4319-a77f-73e7a0d3b7c9)
![25079A93595900FC4503FDCD59164424](https://github.com/slu4coder/The-Minimal-64-Home-Computer/assets/61811583/223b51ed-18c6-4f8f-bc81-49c1f7f75d64)

**Comment by slu4coder** [comment]
Hi denjhang,
welcome to this corner of the internet. Your Minimal 64 looks great. Sad to hear that it refuses to work. I have never tried the RAM IC you mention but it seems to be pin compatible to the one I have used. From afar, it is not easy to give you good advice here. I would start to re-inspect every soldering joint first, then look for any bent pins (happened to me the other day), then re-check the type and orientation of all ICs. Does the UART send a specific number of bytes upon pressing reset? It is supposed to send "READY." plus a line feed, 7 chars in total. For debugging there is an image you can try and burn into the FLASH for testing.

**Comment by denjhang** [comment]
I made sure I had correctly burned the ROM into the chip, I'm using a TL866II+.
I have replaced AS6C1008, and I have also replaced all 74 chips with original chips. However, nothing happens when I press the reset button this time.

**Comment by denjhang** [comment]
https://github.com/slu4coder/The-Minimal-64-Home-Computer/tree/main/Revision%201.2/FLASH%20Images/debug

It looks like there is a debug ROM here that I can try.

**Comment by denjhang** [comment]
I thought I should make another Minimal UART CPU and Gigatron to verify the usability of the 74 chip.

**Comment by slu4coder** [comment]
It can be helpful to only use new ICs from "trusted" sources rather than used ones or older ICs of unclear origins. This can save a lot of trouble. It might be a good idea to burn the debug FLASH images for testing to make sure the CPU shows basic signs of life. But to make any sort of progress here, we need to collect more data, make some additional measurements. I suggest to take a look at the following:

1) Make sure that all ICs see a nice and stable supply voltage of 5V. Measure the supply voltage on of each IC (top right pin).
2) Make sure the Clock oscillator outputs a proper 16MHz signal.
3) Make sure you have valid 8MHz, 4MHz and 2MHz clock signals (U50, pins 14, 13, 12).
4) Take a look at ~VSYNC (act low every 16.7ms) and ~HSYNC (act low every 32µs).

Then you should be able to see at least a stable (maybe still random) video output on you VGA display since the VGA is quite independent of the CPU.

Only then I'd recommend trying the debug images. Good luck!

**Comment by slu4coder** [comment]
denjhang, since you are not requesting to change a certain specific issue here, let's continue trouble-shooting in the discussions section. Please start a new discussion there if you need further assistance.
