### ISSUE TITLE
Non-Windows Emulator?

### ISSUE THREAD

**Issue by michaelkamprath** [slu4coder/The-Minimal-64-Home-Computer#4]
Any chance of you sharing the emulator source code so an adventurous soul can port it to something other than a Windows application?

**Comment by slu4coder** [comment]
Hi Michael,

sorry, the emulator source will not be part of the Minimal 64 project. Way too much OpenGL stuff in there. I want to avoid having to answer questions about that ;-)

However, I might release a Linux version since some years ago I knew how to do that. So I figure I could learn it again quickly. My code is more or less portable and requires minimal adaptions. We'll see.

Cheers!

**Comment by lindoran** [comment]
going through the answered stuff to see if my question was already answered... I did manage to get the emulator to work under a fairly normal wine install on my Q4OS KDE/Debian install. no issues; hope this helps

**Comment by michaelkamprath** [comment]
I was not able to get the emulator running using Wine on MacOS.

**Comment by lindoran** [comment]
It simply launched under my distributions debian builds preconfigured
package of wine. I wonder what the issue could be?  - did you install from
a preconfigured package or compile it?

**Comment by slu4coder** [comment]
Guys, I have just ported my emulator to the Processing/Java environment just for fun and will publish the source code shortly. This should allow anyone to launch it anywhere and also tinker around with it's inner workings. The emulator is conceptually quite "minimal" as you might already have guessed :-)

**Comment by lindoran** [comment]
Most excellent :)

**Comment by slu4coder** [comment]
@ Michael: I've added a simple (yet fully functional) Java/Processing version of the emulator. This should solve any portability issues.

**Comment by michaelkamprath** [comment]
I got it working, thanks! Now to look into writing my own code for this computer,
