### ISSUE TITLE
way to change the keyboard layout (at least on the emulator)

### ISSUE THREAD

**Issue by lindoran** [slu4coder/The-Minimal-64-Home-Computer#6]
I know the whole point of the computer is to be minimal and things like a new keyboard layout would make the whole build less minimal but the UK layout moves the quotation marks  over the two (among other things). Would it be possible to allow for other keyboard layouts inside the emulator?  To allow for a us or standard 101 keyboard layout?

**Comment by slu4coder** [comment]
Hi, Dave,
the whole issue of different keyboard layouts isn't easy for me to solve, since I can't test. Here are a few thoughts:

On the Minimal 64 hardware the PS2 scancodes are translated into Minimal keycodes (ASCII wherever possible) via a lookup table as part of MinOS. You can easily change this lookup table inside os.asm, re-assemble and update the OS via 'flash' as described in the manual. I already provide a German and US keyboard table snippet in the repo.

On the emulator things get more complicated. Your (local) OS will send OpenGL keycodes to the application. The application translates these into PS2 scancodes and finally MinOS translates them back into Minimal keycodes as described above. Any mismatch and you won't find your quotation marks.

At this stage I haven't exposed the GLFW keycode -> PS2 scancode table of the emulator. I'll look into it.

**Comment by lindoran** [comment]
Thank you for such a quick response :) I figured it was complicated but at
least there's a live hardware fix. I wonder if I can play around with the
settings in wine to mimic a UK keyboard, that would at least fix the issue
on linux, it's a hack but it might work out as a fix that leads to the
solution. At least knowing how that works makes trying to find a work
around more straight forward.  I will test this weekend and let you know

**Comment by slu4coder** [comment]
I've added a simple (yet fully functional) Java/Processing version of the emulator. This should solve any portability issues.
Let me know what you think.
